#!/usr/bin/env bash
set -euo pipefail

# Recreates James' zsh environment on a fresh Linux machine.
# Usage: ./setup-zsh.sh

SCRIPT_NAME="$(basename "$0")"
ZSHRC_PATH="${HOME}/.zshrc"
OH_MY_ZSH_DIR="${HOME}/.oh-my-zsh"
OH_MY_ZSH_CUSTOM="${ZSH_CUSTOM:-${OH_MY_ZSH_DIR}/custom}"

log() {
  printf '[%s] %s\n' "${SCRIPT_NAME}" "$*"
}

detect_pkg_manager() {
  if command -v apt-get >/dev/null 2>&1; then
    echo "apt"
    return
  fi
  if command -v dnf >/dev/null 2>&1; then
    echo "dnf"
    return
  fi
  if command -v pacman >/dev/null 2>&1; then
    echo "pacman"
    return
  fi
  echo ""
}

install_base_packages() {
  local needed=()
  for cmd in zsh git curl; do
    command -v "${cmd}" >/dev/null 2>&1 || needed+=("${cmd}")
  done

  if [[ ${#needed[@]} -eq 0 ]]; then
    log "zsh, git, and curl already installed; skipping package manager."
    return
  fi

  log "Missing: ${needed[*]}"

  local pkg_manager
  pkg_manager="$(detect_pkg_manager)"

  case "${pkg_manager}" in
    apt)
      log "Installing base packages with apt..."
      sudo apt-get install -y "${needed[@]}" ca-certificates
      ;;
    dnf)
      log "Installing base packages with dnf..."
      sudo dnf install -y "${needed[@]}" ca-certificates
      ;;
    pacman)
      log "Installing base packages with pacman..."
      sudo pacman -S --needed --noconfirm "${needed[@]}" ca-certificates
      ;;
    *)
      log "No supported package manager detected (apt/dnf/pacman)."
      log "Install zsh, git, and curl manually, then re-run ${SCRIPT_NAME}."
      exit 1
      ;;
  esac
}

ensure_local_bin_in_path() {
  local local_bin="${HOME}/.local/bin"
  mkdir -p "${local_bin}"
  case ":${PATH}:" in
    *":${local_bin}:"*) log "${local_bin} already in PATH." ;;
    *)
      log "Adding ${local_bin} to PATH."
      export PATH="${local_bin}:${PATH}"
      ;;
  esac
}

install_oh_my_zsh() {
  if [[ -d "${OH_MY_ZSH_DIR}" ]]; then
    log "oh-my-zsh already installed."
    return
  fi

  log "Installing oh-my-zsh..."
  RUNZSH=no CHSH=no KEEP_ZSHRC=yes \
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
}

clone_or_update_repo() {
  local repo_url="$1"
  local target_dir="$2"

  if [[ -d "${target_dir}/.git" ]]; then
    log "Updating $(basename "${target_dir}")..."
    git -C "${target_dir}" pull --ff-only
    return
  fi

  if [[ -d "${target_dir}" ]]; then
    log "Directory exists but is not a git repo: ${target_dir}"
    return
  fi

  log "Cloning ${repo_url}..."
  git clone --depth=1 "${repo_url}" "${target_dir}"
}

install_plugins() {
  mkdir -p "${OH_MY_ZSH_CUSTOM}/plugins"

  clone_or_update_repo \
    "https://github.com/zsh-users/zsh-autosuggestions" \
    "${OH_MY_ZSH_CUSTOM}/plugins/zsh-autosuggestions"

  clone_or_update_repo \
    "https://github.com/zsh-users/zsh-syntax-highlighting" \
    "${OH_MY_ZSH_CUSTOM}/plugins/zsh-syntax-highlighting"
}

install_starship() {
  if command -v starship >/dev/null 2>&1; then
    log "starship already installed."
    return
  fi

  log "Installing starship..."
  curl -fsSL https://starship.rs/install.sh | sh -s -- -y -b "${HOME}/.local/bin"
  hash -r
}

configure_starship() {
  mkdir -p "${HOME}/.config"
  log "Applying starship gruvbox-rainbow preset..."
  "${HOME}/.local/bin/starship" preset gruvbox-rainbow -o "${HOME}/.config/starship.toml"
}

install_uv() {
  if command -v uv >/dev/null 2>&1; then
    log "uv already installed."
    return
  fi

  log "Installing uv..."
  curl -LsSf https://astral.sh/uv/install.sh | sh
}

write_zshrc() {
  if [[ -f "${ZSHRC_PATH}" ]]; then
    local backup_path
    backup_path="${ZSHRC_PATH}.bak.$(date +%Y%m%d-%H%M%S)"
    cp "${ZSHRC_PATH}" "${backup_path}"
    log "Backed up existing .zshrc to ${backup_path}"
  fi

  cat >"${ZSHRC_PATH}" <<EOF
# Generated by ${SCRIPT_NAME} on $(date -Iseconds)
export ZSH="\$HOME/.oh-my-zsh"

plugins=(git zsh-autosuggestions zsh-syntax-highlighting)
source \$ZSH/oh-my-zsh.sh

case ":\$PATH:" in
  *":\$HOME/.local/bin:"*) ;;
  *) export PATH="\$HOME/.local/bin:\$PATH" ;;
esac

eval "\$(starship init zsh)"
eval "\$(uv generate-shell-completion zsh)"
export LANG=en_US.UTF-8

# Put machine-specific or secret values in ~/.zshrc.local
if [[ -f \$HOME/.zshrc.local ]]; then
  source \$HOME/.zshrc.local
fi
EOF

}

set_default_shell() {
  # CI and other non-interactive environments should not attempt shell changes.
  if [[ -n "${CI:-}" ]]; then
    log "CI environment detected; skipping default shell change."
    return
  fi

  if [[ ! -t 0 ]]; then
    log "Non-interactive session detected; skipping default shell change."
    return
  fi

  if [[ "${SHELL:-}" == *"zsh" ]]; then
    log "Default shell already zsh."
    return
  fi

  if ! command -v zsh >/dev/null 2>&1; then
    log "zsh not found in PATH; skipping chsh."
    return
  fi

  if ! command -v chsh >/dev/null 2>&1; then
    log "chsh not found; skipping default shell change."
    return
  fi

  log "Changing default shell to zsh..."
  if ! chsh -s "$(command -v zsh)"; then
    log "Unable to change default shell automatically. Please run chsh manually."
  fi
}

main() {
  install_base_packages
  ensure_local_bin_in_path
  install_oh_my_zsh
  install_plugins
  install_starship
  configure_starship
  install_uv
  write_zshrc
  set_default_shell

  log "Setup complete."
  log "Run: source ~/.zshrc"
}

main "$@"
